apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app
spec:
  params:
    - name: DEPLOYMENT_NAME
      description: The name of deployment
      type: string
    - name: CONTAINER_NAME
      description: The name of deployment
      type: string
    - name: NAMESPACE
      description: The namespace for the deployment
      type: string
    - name: IMAGE
      description: The image from OpenShift registry to be deployed e.g. imagestream:tag
    - name: KUSTOMIZE_OVERLAY_DIR
      description: The subdirectory in configs git repo for the kustomize overlay to be applied
  resources:
    inputs:
    - name: config
      type: git
  steps:
    - name: apply-manifests
      workingDir: /workspace/config
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash

        image_digest=$(oc get istag $(params.IMAGE) -n $(params.NAMESPACE) -o template --template='{{.image.dockerImageReference}}')
        cat << EOF >> /workspace/config/$(params.KUSTOMIZE_OVERLAY_DIR)/kustomization.yaml
        
        images:
        - name: quay.io/siamaksade/spring-petclinic:latest
          newName: ${image_digest%@*}
          digest: ${image_digest#*@}
        EOF

        oc apply -k $(params.KUSTOMIZE_OVERLAY_DIR) -n $(params.NAMESPACE)
        oc rollout status deploy/$(params.DEPLOYMENT_NAME) -n $(params.NAMESPACE)
